name: ceres
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  http: ^1.3.0
  flutter_inappwebview: ^6.1.5
  permission_handler: ^11.3.1
  connectivity_plus: ^6.1.3
  shared_preferences: ^2.5.2
  flutter_background_geolocation: ^4.16.10
  syncfusion_flutter_pdfviewer: ^28.2.9
  l10n_flutter: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/better_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/better_logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/better_logo.png"
  android: true
  ios: true

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/google_logo.png
    - assets/logo_connection_out.png
    - assets/better_logo.png

l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart